name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]

    steps:
      - uses: actions/checkout@v6

      # https://github.com/orgs/community/discussions/26686#discussioncomment-3252850
      - name: Extract tag name
        id: tag
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/^refs\/tags\/v/, '');

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: '*/packages.lock.json'

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore --configuration Release -p:VersionPrefix=${{ steps.tag.outputs.result }}

      - name: Unit Tests
        run: dotnet test --no-build --configuration Release

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            **/*.nupkg

      - name: Publish
        if: github.ref_type == 'tag'
        run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
